s1[0]="A"
s1[1]="B"
s1[2]="D"
s1[image]="loriringhio97/p4"


s2[0]="C"
s2[1]="B"
s2[2]="D"
s2[image]="loriringhio97/p4"


modbusclient[0]="A"
modbusclient[image]="loriringhio97/modbus"


modbusserver[0]="C"
modbusserver[image]="loriringhio97/modbus"

wireshark[0]="A"
wireshark[1]="B"
wireshark[2]="C"
wireshark[bridged]=true
wireshark[port]="3000:3000/tcp"
wireshark[image]="lscr.io/linuxserver/wireshark"

registry[0]="L"
registry[port]="8082:4000/tcp"
registry[bridged]=true
registry[env]="basyxcontext_accesscontrolalloworigin=*"
registry[image]="loriringhio97/kathara_basyx_registry"

server[0]="L"
server[port]="8081:4001/tcp"
server[bridged]=true
server[env]="basyxcontext_accesscontrolalloworigin=*"
server[image]="loriringhio97/kathara_basyx_server"

webui[0]="L"
webui[port]="3001:3000/tcp"
webui[bridged]=true
webui[shell]="/bin/sh"
webui[env]="basyxcontext_accesscontrolalloworigin=*"
webui[env]="VITE_REGISTRY_PATH=http://localhost:8082/registry"
webui[image]="loriringhio97/aas-gui:v230703"
# webui[image]="eclipsebasyx/aas-gui:v2-260505"

compat[0]="L"
compat[port]="9081:9081/tcp"
compat[port]="9082:9082/tcp"
compat[port]="9083:9083/tcp"
compat[port]="9084:9084/tcp"
compat[bridged]=true
compat[shell]="/bin/sh"
compat[env]="REGISTRY_URL=http://172.17.0.1:8082/registry/api/v1/registry"
compat[env]="LOCAL_HOST=localhost"
compat[env]="BIND_HOST=0.0.0.0"
compat[env]="BACKEND_HOST=172.17.0.1"


aas_project[0]="L"
aas_project[1]="D"
aas_project[2]="A"
aas_project[3]="C"
aas_project[bridged]=true
aas_project[port]="6001:6001/tcp"
aas_project[port]="6002:6002/tcp"
aas_project[port]="6003:6003/tcp"
aas_project[port]="6004:6004/tcp"
aas_project[image]="loriringhio97/kathara_jdk"
