aas.backend=InMemory
aas.source=
aas.events=NONE
aas.id=aas-server
aas.aasxUpload=Enabled
aas.authorization=Disabled
aas.delegation=Enabled
registry.path=
registry.host=
registry.submodels=[]
tokenEndpoint=
clientId=
clientSecret=
clientScopes=[]
